class Location

  include Neo4j::NodeMixin

  property :apt_office_floor_number, :street_number, :street_name, :street_type, :suburb, :city, :country, :postcode, :notes
  
  has_n(:location_to_person).to(Person).relationship(Role)
  has_n(:location_to_organisation).to(Organisation).relationship(Role)
  has_n(:location_to_event).to(Event).relationship(Role)
  has_n(:location_to_location).to(Location).relationship(Role)
  has_n(:location_to_reference).to(Reference).relationship(Role)

  has_n(:person_to_location).from(Person).relationship(Role)
  has_n(:organisation_to_location).from(Organisation).relationship(Role)
  has_n(:event_to_location).from(Event).relationship(Role)
  has_n(:reference_to_location).from(Reference).relationship(Role)

  index :street_name, :suburb, :country

  Location::LOCATION_TYPES = [
    ["Street","Street"],
    ["Avenue","Avenue"],
    ["Highway","Highway"],
    ["Place","Place"],
    ["Crescent","Crescent"],
    ["Boulevard","Boulevard"],
    ["Other","Other"]
  ]
  
  Location::COUNTRIES = [
    ["United Kingdom","United Kingdom"],
    ["United States","United States"],
    ["Australia","Australia"],
    ["Chile","Chile"],
    ["China","China"],
    ["Afghanistan","Afghanistan"],
    ["Africa","Africa"],
    ["Albania","Albania"],
    ["Algeria","Algeria"],
    ["American Samoa","American Samoa"],
    ["Andorra","Andorra"],
    ["Angola","Angola"],
    ["Anguilla","Anguilla"],
    ["Antarctica","Antarctica"],
    ["Antigua & Barbuda","Antigua & Barbuda"],
    ["Antilles, Netherlands","Antilles, Netherlands"],
    ["Arabia, Saudi","Arabia, Saudi"],
    ["Argentina","Argentina"],
    ["Armenia","Armenia"],
    ["Aruba","Aruba"],
    ["Asia","Asia"],
    ["Austria","Austria"],
    ["Azerbaijan","Azerbaijan"],
    ["Bahamas, The","Bahamas, The"],
    ["Bahrain","Bahrain"],
    ["Bangladesh","Bangladesh"],
    ["Barbados","Barbados"],
    ["Belarus","Belarus"],
    ["Belgium","Belgium"],
    ["Belize","Belize"],
    ["Benin","Benin"],
    ["Bermuda","Bermuda"],
    ["Bhutan","Bhutan"],
    ["Bolivia","Bolivia"],
    ["Bosnia and Herzegovina","Bosnia and Herzegovina"],
    ["Botswana","Botswana"],
    ["Bouvet Island","Bouvet Island"],
    ["Brazil","Brazil"],
    ["British Indian Ocean T.","British Indian Ocean T."],
    ["British Virgin Islands","British Virgin Islands"],
    ["Brunei Darussalam","Brunei Darussalam"],
    ["Bulgaria","Bulgaria"],
    ["Burkina Faso","Burkina Faso"],
    ["Burundi","Burundi"],
    ["Cambodia","Cambodia"],
    ["Cameroon","Cameroon"],
    ["Canada","Canada"],
    ["Cape Verde","Cape Verde"],
    ["Caribbean, the","Caribbean, the"],
    ["Cayman Islands","Cayman Islands"],
    ["Central African Republic","Central African Republic"],
    ["Central America","Central America"],
    ["Chad","Chad"],
    ["Christmas Island","Christmas Island"],
    ["Cocos (Keeling) Islands","Cocos (Keeling) Islands"],
    ["Colombia","Colombia"],
    ["Comoros","Comoros"],
    ["Congo","Congo"],
    ["Congo, Dem. Rep. of the","Congo, Dem. Rep. of the"],
    ["Cook Islands","Cook Islands"],
    ["Costa Rica","Costa Rica"],
    ["Cote D'Ivoire","Cote D'Ivoire"],
    ["Croatia","Croatia"],
    ["Cuba","Cuba"],
    ["Cyprus","Cyprus"],
    ["Czech Republic","Czech Republic"],
    ["Denmark","Denmark"],
    ["Djibouti","Djibouti"],
    ["Dominica","Dominica"],
    ["Dominican Republic","Dominican Republic"],
    ["East Timor (Timor-Leste)","East Timor (Timor-Leste)"],
    ["Ecuador","Ecuador"],
    ["Egypt","Egypt"],
    ["El Salvador","El Salvador"],
    ["Equatorial Guinea","Equatorial Guinea"],
    ["Eritrea","Eritrea"],
    ["Estonia","Estonia"],
    ["Ethiopia","Ethiopia"],
    ["Europe","Europe"],
    ["European Union","European Union"],
    ["Falkland Islands (Malvinas)","Falkland Islands (Malvinas)"],
    ["Faroe Islands","Faroe Islands"],
    ["Fiji","Fiji"],
    ["Finland","Finland"],
    ["France","France"],
    ["French Guiana","French Guiana"],
    ["French Polynesia","French Polynesia"],
    ["French Southern Terr.","French Southern Terr."],
    ["Gabon","Gabon"],
    ["Gambia, the","Gambia, the"],
    ["Georgia","Georgia"],
    ["Germany","Germany"],
    ["Ghana","Ghana"],
    ["Gibraltar","Gibraltar"],
    ["Greece","Greece"],
    ["Greenland","Greenland"],
    ["Grenada","Grenada"],
    ["Guadeloupe","Guadeloupe"],
    ["Guam","Guam"],
    ["Guatemala","Guatemala"],
    ["Guernsey and Alderney","Guernsey and Alderney"],
    ["Guiana, French","Guiana, French"],
    ["Guinea","Guinea"],
    ["Guinea-Bissau","Guinea-Bissau"],
    ["Guinea, Equatorial","Guinea, Equatorial"],
    ["Guyana","Guyana"],
    ["Haiti","Haiti"],
    ["Heard & McDonald Is.(AU)","Heard & McDonald Is.(AU)"],
    ["Holy See (Vatican)","Holy See (Vatican)"],
    ["Honduras","Honduras"],
    ["Hong Kong, (China)","Hong Kong, (China)"],
    ["Hungary","Hungary"],
    ["Iceland","Iceland"],
    ["India","India"],
    ["Indonesia","Indonesia"],
    ["Iran, Islamic Republic of","Iran, Islamic Republic of"],
    ["Iraq","Iraq"],
    ["Ireland","Ireland"],
    ["Israel","Israel"],
    ["Italy","Italy"],
    ["Ivory Coast (Cote d'Ivoire)","Ivory Coast (Cote d'Ivoire)"],
    ["Jamaica","Jamaica"],
    ["Japan","Japan"],
    ["Jersey","Jersey"],
    ["Jordan","Jordan"],
    ["Kazakhstan","Kazakhstan"],
    ["Kenya","Kenya"],
    ["Kiribati","Kiribati"],
    ["Korea Dem. People's Rep.","Korea Dem. People's Rep."],
    ["Korea, (South) Republic of","Korea, (South) Republic of"],
    ["Kosovo","Kosovo"],
    ["Kuwait","Kuwait"],
    ["Kyrgyzstan","Kyrgyzstan"],
    ["Lao People's Democ. Rep.","Lao People's Democ. Rep."],
    ["Latvia","Latvia"],
    ["Lebanon","Lebanon"],
    ["Lesotho","Lesotho"],
    ["Liberia","Liberia"],
    ["Libyan Arab Jamahiriya","Libyan Arab Jamahiriya"],
    ["Liechtenstein","Liechtenstein"],
    ["Lithuania","Lithuania"],
    ["Luxembourg","Luxembourg"],
    ["Macao, (China)","Macao, (China)"],
    ["Macedonia, TFYR","Macedonia, TFYR"],
    ["Madagascar","Madagascar"],
    ["Malawi","Malawi"],
    ["Malaysia","Malaysia"],
    ["Maldives","Maldives"],
    ["Mali","Mali"],
    ["Malta","Malta"],
    ["Man, Isle of","Man, Isle of"],
    ["Marshall Islands","Marshall Islands"],
    ["Martinique (FR)","Martinique (FR)"],
    ["Mauritania","Mauritania"],
    ["Mauritius","Mauritius"],
    ["Mayotte (FR)","Mayotte (FR)"],
    ["Mexico","Mexico"],
    ["Micronesia, Fed. States of","Micronesia, Fed. States of"],
    ["Middle East","Middle East"],
    ["Moldova, Republic of","Moldova, Republic of"],
    ["Monaco","Monaco"],
    ["Mongolia","Mongolia"],
    ["Montenegro","Montenegro"],
    ["Montserrat","Montserrat"],
    ["Morocco","Morocco"],
    ["Mozambique","Mozambique"],
    ["Myanmar (ex-Burma)","Myanmar (ex-Burma)"],
    ["Namibia","Namibia"],
    ["Nauru","Nauru"],
    ["Nepal","Nepal"],
    ["Netherlands","Netherlands"],
    ["Netherlands Antilles","Netherlands Antilles"],
    ["New Caledonia","New Caledonia"],
    ["New Zealand","New Zealand"],
    ["Nicaragua","Nicaragua"],
    ["Niger","Niger"],
    ["Nigeria","Nigeria"],
    ["Niue","Niue"],
    ["Norfolk Island","Norfolk Island"],
    ["North America","North America"],
    ["Northern Mariana Islands","Northern Mariana Islands"],
    ["Norway","Norway"],
    ["Oceania","Oceania"],
    ["Oman","Oman"],
    ["Pakistan","Pakistan"],
    ["Palau","Palau"],
    ["Palestinian Territory","Palestinian Territory"],
    ["Panama","Panama"],
    ["Papua New Guinea","Papua New Guinea"],
    ["Paraguay","Paraguay"],
    ["Peru","Peru"],
    ["Philippines","Philippines"],
    ["Pitcairn Island","Pitcairn Island"],
    ["Poland","Poland"],
    ["Portugal","Portugal"],
    ["Puerto Rico","Puerto Rico"],
    ["Qatar","Qatar"],
    ["Reunion (FR)","Reunion (FR)"],
    ["Romania","Romania"],
    ["Russia (Russian Fed.)","Russia (Russian Fed.)"],
    ["Rwanda","Rwanda"],
    ["Sahara, Western","Sahara, Western"],
    ["Saint Barthelemy (FR)","Saint Barthelemy (FR)"],
    ["Saint Helena (UK)","Saint Helena (UK)"],
    ["Saint Kitts and Nevis","Saint Kitts and Nevis"],
    ["Saint Lucia","Saint Lucia"],
    ["Saint Martin (FR)","Saint Martin (FR)"],
    ["S Pierre & Miquelon (FR)","S Pierre & Miquelon (FR)"],
    ["S Vincent & Grenadines","S Vincent & Grenadines"],
    ["Samoa","Samoa"],
    ["San Marino","San Marino"],
    ["Sao Tome and Principe","Sao Tome and Principe"],
    ["Saudi Arabia","Saudi Arabia"],
    ["Senegal","Senegal"],
    ["Serbia","Serbia"],
    ["Seychelles","Seychelles"],
    ["Sierra Leone","Sierra Leone"],
    ["Singapore","Singapore"],
    ["Slovakia","Slovakia"],
    ["Slovenia","Slovenia"],
    ["Solomon Islands","Solomon Islands"],
    ["Somalia","Somalia"],
    ["South Africa","South Africa"],
    ["South America","South America"],
    ["S.George & S.Sandwich","S.George & S.Sandwich"],
    ["Spain","Spain"],
    ["Sri Lanka (ex-Ceilan)","Sri Lanka (ex-Ceilan)"],
    ["Sudan","Sudan"],
    ["Suriname","Suriname"],
    ["Svalbard & Jan Mayen Is.","Svalbard & Jan Mayen Is."],
    ["Swaziland","Swaziland"],
    ["Sweden","Sweden"],
    ["Switzerland","Switzerland"],
    ["Syrian Arab Republic","Syrian Arab Republic"],
    ["Taiwan","Taiwan"],
    ["Tajikistan","Tajikistan"],
    ["Tanzania, United Rep. of","Tanzania, United Rep. of"],
    ["Thailand","Thailand"],
    ["Timor-Leste (East Timor)","Timor-Leste (East Timor)"],
    ["Togo","Togo"],
    ["Tokelau","Tokelau"],
    ["Tonga","Tonga"],
    ["Trinidad & Tobago","Trinidad & Tobago"],
    ["Tunisia","Tunisia"],
    ["Turkey","Turkey"],
    ["Turkmenistan","Turkmenistan"],
    ["Turks and Caicos Islands","Turks and Caicos Islands"],
    ["Tuvalu","Tuvalu"],
    ["Uganda","Uganda"],
    ["Ukraine","Ukraine"],
    ["United Arab Emirates","United Arab Emirates"],
    ["US Minor Outlying Isl.","US Minor Outlying Isl."],
    ["Uruguay","Uruguay"],
    ["Uzbekistan","Uzbekistan"],
    ["Vanuatu","Vanuatu"],
    ["Vatican (Holy See)","Vatican (Holy See)"],
    ["Venezuela","Venezuela"],
    ["Viet Nam","Viet Nam"],
    ["Virgin Islands, British","Virgin Islands, British"],
    ["Virgin Islands, U.S.","Virgin Islands, U.S."],
    ["Wallis and Futuna","Wallis and Futuna"],
    ["Western Sahara","Western Sahara"],
    ["Yemen","Yemen"],
    ["Zambia","Zambia"],
    ["Zimbabwe","Zimbabwe"]
  ]
  
end